# Generated by Django 4.0 on 2022-01-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Hardness', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Solids', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Chloramines', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Sulfate', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Conductivity', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Organic_carbon', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Trihalomethanes', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('Turbidity', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
            ],
        ),
    ]
