# Generated by Django 4.0 on 2022-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='ph',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
