# Generated by Django 4.0 on 2022-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_quality', '0003_alter_water_chloramines_alter_water_conductivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='Chloramines',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Conductivity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Hardness',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Organic_carbon',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Solids',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Sulfate',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Trihalomethanes',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='Turbidity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='water',
            name='ph',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
